package ie.wit.model.entity;

import javax.persistence.*;

/**
 * Represents a role for authentication.
 * @see ie.wit.model.entity.UserEntity UserEntity
 *
 * @author Joe Wemyss
 *
 */
@Entity
@Table(name = "Role")
public class Role
{
	/**
	 * The Entity Primary key. Generated by the database
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	
	/**
	 * The name of the role.
	 * Must be unique, cannot be null.
	 */
	@Column(name = "name", unique = true)
	@Basic(optional = false)
	private String name;

	/**
	 * Default constructor.
	 * Used by JPA to initialize the Entity
	 */
	protected Role() {}
	
	/**
	 * Constructor
	 * @param String the name of the role
	 */
	public Role(String name){
		this.name = name;
	}

	/**
	 * Accessor for the Primary Key
	 * @return Long the Primary Key
	 */
	public Long getId()
	{
		return id;
	}

	/**
	 * Mutator for the Primary Key
	 * @param Long the Primary key
	 */
	public void setId(Long id)
	{
		this.id = id;
	}

	/**
	 * Accessor for the role name
	 * @return String the role name
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Mutator for the role name
	 * @param String the role name
	 */
	public void setName(String name)
	{
		this.name = name;
	}
}
