package ie.wit.model.entity;

import javax.persistence.*;
import java.util.List;
import java.util.Optional;

/**
 * Represents a user entity for authentication
 *
 * @author Joe Wemyss
 */
@Entity
@Table(name = "User")
public class UserEntity
{
	/**
	 * The Entity Primary key. Generated by the database
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	/**
	 * Users email address.
	 */
	@Basic(optional = false)
	@Column(name = "email_address", unique = true)
	private String emailAddress;

	@Column(name = "first_name")
	private String firstName;

	@Column(name = "surname")
	private String surname;

	@ManyToMany()
	@JoinTable(
			name = "User_roles",
			joinColumns = @JoinColumn(name = "user", referencedColumnName = "id"),
			inverseJoinColumns = @JoinColumn(name = "role", referencedColumnName = "id")
	)
	private List<Role> roles;

	protected UserEntity(){}


	public Optional<String> getFirstName(){
		return Optional.ofNullable(firstName);
	}
	public Optional<String> getSurname(){
		return Optional.ofNullable(surname);
	}

	public Long getId()
	{
		return id;
	}

	public String getEmailAddress()
	{
		return emailAddress;
	}

	public List<Role> getRoles()
	{
		return roles;
	}
	public  void addRole(Role role){
		roles.add(role);
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public void setEmailAddress(String emailAddress)
	{
		this.emailAddress = emailAddress;
	}

	public void setFirstName(String firstName)
	{
		this.firstName = firstName;
	}

	public void setSurname(String surname)
	{
		this.surname = surname;
	}

	public void setRoles(List<Role> roles)
	{
		this.roles = roles;
	}
}
